# -*- coding: utf-8 -*-
"""Apriori_Recommender.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MnL5sqYThRaurkdrughtMee42jLJBPht
"""

# from google.colab import drive
# drive.mount('/content/drive', force_remount=True)

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/My Drive/Colab Notebooks/'
# %run Data_Parser.ipynb
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

print('')# just used to pretty up the output by adding a space after the initial cmd command

game_df = get_user_game_sparse_matrix()

print('Executing Apriori algorithm...')

freq_gamesets = apriori(game_df, min_support=0.01, min_conf=, use_colnames=True) # 6.5 hour runtime
print(freq_gamesets)

rules = association_rules(freq_gamesets, metric='lift', min_threshold=1)
pd.set_option('display.max_columns', None)
print(rules)

print('Done.')